### ISSUE TITLE
Add an endpoint for getting diagnostic info about a given lock

### ISSUE THREAD

**Issue by inlinestyle** [gamechanger/lox#6]
It would help with debugging applications that use Lox if there were a way to check how many lock ids were checked out for a given lock.

I'm thinking something like
```javascript
GET /lock?key=<my-lock-key>
```
That would return some JSON
```javascript
{
    "heldLocks": 5
}
```

**Comment by thieman** [comment]
+1

**Comment by inlinestyle** [comment]
Woooo
